---
name: Set-Tiny
version: 0.01
author:
  - 'Stanis Trendelenburg <stanis.trendelenburg@gmail.com>'
abstract: simple sets of strings
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Set::Tiny:
    file: lib/Set/Tiny.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
